### ISSUE TITLE
Configuration for a django-adminsortable2 inline-tabular form is invalid.

### ISSUE THREAD

**Issue by jpark2320** [jrief/django-admin-sortable2#217]
I followed the installation and usage instructions, and I used `SortableInlineAdminMixin` for my TabularInline.

```
class ImageInline(SortableInlineAdminMixin, admin.TabularInline):
    model = Image


@admin.register(Store)
class StoreAdmin(admin.ModelAdmin):
    form = StoreForm
    inlines = [
        ImageInline,
    ]
```

When I get into the page for Store in Django admin, the form breaks and it throws the following error on the console on the file `adminsortable2/js/inline-tabular.js`.

`Configuration for a django-adminsortable2 inline-tabular form is invalid.`

**Comment by stefanw** [comment]
This seems to have been fixed in 314e3aa1ea6f31e54ea3e7279ce1b94c9b145b44 which is not released yet. @jrief

**Comment by mgrdcm** [comment]
Running into this too...  Happy to help in any way I can - anything I can do to help get a release out that includes 
https://github.com/jrief/django-admin-sortable2/commit/314e3aa1ea6f31e54ea3e7279ce1b94c9b145b44 @jrief?

**Comment by jrief** [comment]
should be fixed in 0.7

**Comment by razisayyed** [comment]
I am still having the same error after upgrading to 0.7. 
I am using Django 2.1.
