### ISSUE TITLE
SortableInlineAdminMixin does not work after 2.0

### ISSUE THREAD

**Issue by michelematera** [jrief/django-admin-sortable2#304]
After updating to 2.0, the drag and drop button no longer appears in TabularInline.
Downgrading to 1.0.4 everything works fine.

```
class PageLinkInline(SortableInlineAdminMixin, admin.TabularInline):
    model = models.PageLink
    extra = 0
    fk_name = 'page'
    raw_id_fields = ['page_child']
    ordering = ['position']
```

I am using Django==4.0.3.

**Comment by jrief** [comment]
Please read [how to report bugs](https://github.com/jrief/django-admin-sortable2/blob/master/docs/source/contributing.rst#reporting-bugs).

After that, if you point the browser on
http://localhost:8000/admin/testapp/sortablebook3/17/change/
you get a demo with a `TabularInline`.

Please report bugs based on that demo.

**Comment by jrief** [comment]
fixed in version 2.0.3

**Comment by michelematera** [comment]
The bug was not fixed. Up to version 1.0.4 it was not necessary to inherit SortableAdminMixin to SortableBookAdmin to sort the inlines. This is a big limitation.

**Comment by jrief** [comment]
The parent admin class now must inherit from `SortableAdminBase` in order to make inlines sortable. The alternative would be to override the templates, something I definitely do not want to do. Why is that a big limitation for you?

https://github.com/jrief/django-admin-sortable2/blob/master/docs/source/usage.rst#in-djangos-admin-detail-view-make-stacked--and-tabular-inlines-sortable

**Comment by michelematera** [comment]
Forgive me, I hadn't read about SortableAdminBase. Actually from my point of view it would be more convenient to insert everything in SortableInlineAdminMixin as initially there was up to 1.0.4 but that's okay too. Thanks

**Comment by jrief** [comment]
> Actually from my point of view it would be more convenient to insert everything in SortableInlineAdminMixin as initially there was up to 1.0.4

yes, that would be nice. Unfortunately the API designed around Django-4.0 doesn't offer this out of the box. The alternative would have been to continue overriding templates
[tabular.html](https://github.com/jrief/django-admin-sortable2/blob/5cc1c248de1372ffdf76e2331dd871388002201d/adminsortable2/templates/adminsortable2/tabular.html)
and 
[stacked.html](https://github.com/jrief/django-admin-sortable2/blob/5cc1c248de1372ffdf76e2331dd871388002201d/adminsortable2/templates/adminsortable2/stacked.html)
as required until version 1.0.4.

I hope you agree, that the current solution is less error-prone and future-safe.
